services:
  db:
    image: postgres:15.3-alpine
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    environment:
      POSTGRES_PASSWORD: password
  redis:
    image: redis:6.0.16-alpine
    volumes:
      - redis:/data
    ports:
      - '6379:6379'

volumes:
  postgres:
  redis:
