services:
  db:
    image: postgres:15.3-alpine
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    environment:
      POSTGRES_PASSWORD: password
      
volumes:
  postgres:
